spring.profiles.include: diag,debug
apiml:
    service:
        apimlId: apiml1
        hostname: apiml
    discovery:
        staticApiDefinitionsDirectories: /api-defs;/docker/api-defs
        allPeersUrls: https://apiml:10011/eureka
    security:
        allowTokenRefresh: true
        personalAccessToken:
            enabled: true
        oidc:
            enabled: true
            clientId:
            clientSecret:
            registry:
            identityMapperUrl:
            identityMapperUser:
            jwks:
                uri:
        auth:
            zosmf:
                serviceId: mockzosmf  # Replace me with the correct z/OSMF service id
        x509:
            enabled: true
        useDummyCNMapper: true
        saf:
            urls:
                authenticate: https://mock-services:10013/zss/saf/authenticate
                verify: https://mock-services:10013/zss/saf/verify
        ssl:
            verifySslCertificatesOfServices: true
    banner: console
spring:
    output:
        ansi:
            enabled: always
    profiles:
        include: diag

eureka:
    client:
        instanceInfoReplicationIntervalSeconds: 30
        registryFetchIntervalSeconds: 30

management:
    endpoints:
        migrate-legacy-ids: true
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            access: unrestricted

server:
    address: 0.0.0.0
    max-http-header-size: 40000
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: /docker/all-services.keystore.p12
        keyStorePassword: password
        trustStore: /docker/all-services.truststore.p12
        trustStorePassword: password
