apiml:
    service:
        discoveryServiceUrls: https://discovery-service:10011/eureka/
        hostname: caching-service
    banner: console

server:
    address: 0.0.0.0
    ssl:
        keyAlias: localhost
        keyStore: /docker/all-services.keystore.p12
        trustStore: /docker/all-services.truststore.p12
spring:
    output:
        ansi:
            enabled: always
    profiles:
        include: debug
