spring.profiles.include: diag,debug
apiml:
    service:
        apimlId: apiml1
        hostname: gateway-service
        discoveryServiceUrls: https://discovery-service:10011/eureka/
    banner: console
eureka:
    client:
        instanceInfoReplicationIntervalSeconds: 30
        registryFetchIntervalSeconds: 30
spring:
    output:
        ansi:
            enabled: always

management:
    endpoints:
        migrate-legacy-ids: true
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            access: unrestricted

server:
    address: 0.0.0.0
    max-http-header-size: 40000
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: /docker/all-services.keystore.p12
        keyStorePassword: password
        trustStore: /docker/all-services.truststore.p12
        trustStorePassword: password
