apiml:
    service:
        port: 10025
    banner: console
jgroups:
    bind:
        port: 7600
        address: localhost
caching:
    storage:
        mode: infinispan
        infinispan:
            initialHosts: localhost[7099]
spring:
    profiles:
        include: dev
