services:

    redis-master:
        container_name: redis-master
        image: redis:latest
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - C:\Users\jb892003\IdeaProjects\api-layer-v2\redis\master:/usr/local/etc/redis/

    redis-slave:
        container_name: redis-replica
        image: redis:latest
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - C:\Users\jb892003\IdeaProjects\api-layer-v2\redis\replica:/usr/local/etc/redis/
